### ISSUE TITLE
QA checklist

### ISSUE THREAD

**Issue by amadeuspzs** [nhsx/skunkworks-bed-allocation#4]
# Must have:

- [x] Permissive Open Source Licence, for example: MIT Licence
- [x] Documentation: high-level overview
- [x] Documentation: model selection
- [x] Documentation: installation and user guide
- [ ] Code: file input validation
- [ ] Code: legible and explainable
  - [x] Sensible variable/function names
  - [ ] Complex code must be commented
  - [x] Indentation follows accepted practice
- [x] Code: modular
- [x] Security: no data shared (public data linked by URL)
- [x] Security: no serialised models
- [x] Security: no secret keys
- [ ] Web UI: implements [NHS.UK frontend](https://nhsuk.github.io/nhsuk-frontend/)

# Nice to have:

- [ ] Code: automated linting e.g. PEP8
- [x] Data: test (synthetic) data available

# Final check:

- [x] Comms team signoff
